stages:
- name: build
  steps:
  - runScriptConfig:
      image: polinux/stress
      shellScript: stress -m 1 --vm-bytes 2G --vm-keep --timeout 10s
    cpuLimit: 3Gi
    memoryLimit: 3Gi
notification: {}
