stages:
- name: test01
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: centos_nginx:v1
      registry: 127.0.0.1:34377
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: nginx:v2
      registry: 127.0.0.1:34377
  when:
    branch: {}
- name: test2
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
  - applyYamlConfig:
      path: ./deployment2.yaml
  when:
    branch: {}
- name: test03
  steps:
  - {}
  when:
    branch:
      include:
      - aa
timeout: 60
