stages:
- name: test01
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: centos_nginx:v1
      registry: 127.0.0.1:34377
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: nginx:v2
      registry: 127.0.0.1:34377
  when:
    branch:
      include:
      - aa
- name: test2
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
  - applyYamlConfig:
      path: ./deployment2.yaml
  when:
    branch:
      include:
      - aa
- name: test03
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-mariadb
      version: 5.0.9
      name: mariadb
      targetNamespace: default
timeout: 60
notification: {}
