stages:
- name: testaa
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: ls
    cpuLimit: 1G
    cpuRequest: 512M
    memoryLimit: 1G
    memoryRequest: 512M 
timeout: 60
notification: {}
