stages:
- name: test01
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: centos_nginx:v1
      registry: 127.0.0.1:34377
- name: test2
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
